# Generated by Django 4.1.6 on 2023-04-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_forecasttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastTest',
        ),
    ]
